#!/bin/bash

run_it () {
 docker run --rm -it --mount type=bind,source="$(pwd)",target=/MT maker $1
}

if docker image inspect maker > /dev/null  
  then run_it "$1"
  else ./dockerbuild && run_it "$1"
fi
