#!/usr/bin/env python3
"""Call the Assembler for a Token or Macro"""

from argparse import ArgumentParser
from asset import MTAsset
import logging as log

if __name__ == '__main__':
    AP = ArgumentParser(description = "MapTool Asset Assembler")

    AP.add_argument(
            'input',
            nargs='+',
            help='Source for creating the asset')

    AP.add_argument(
            '--list', '--name',
            help='Give a name to a list of macros.  Usually only useful '
                 'if you provide more than one input')

    AP.add_argument(
            '--output',
            help='Output directory')

    AP.add_argument(
            '--verbose',
            action='store_true',
            help='Turn on verbose output')

    av = AP.parse_args()

    if av.verbose:
        log.basicConfig(format="%(levelname)s: %(message)s", level=log.DEBUG)
        log.info("Verbose output.")
    else:
        log.basicConfig(format="%(levelname)s: %(message)s")

    asset = MTAsset(*av.input, name=av.list, path=av.output)
    asset.assemble()
