#!/usr/bin/env python3
"""Call the Assembler for a Token or Macro"""

from argparse import ArgumentParser
from asset import MTAsset
import logging as log
import configparser

if __name__ == '__main__':

    c = configparser.ConfigParser()
    c.read('config.ini')
    if 'default' not in c:
        c['default'] = {}
    if 'outputdirectory' not in c['default']:
        c['default']['outputdirectory'] = '.'

    AP = ArgumentParser(description = "MapTool Asset Assembler")

    AP.add_argument(
            'input',
            nargs='+',
            help='Source for creating the asset')

    AP.add_argument(
            '--list', '--name',
            help='Give a name to a list of macros.  Usually only useful '
                 'if you provide more than one input')

    AP.add_argument(
            '--output',
            default=c['default']['outputdirectory'],
            help='Output directory')

    AP.add_argument(
            '--verbose',
            action='store_true',
            help='Turn on verbose output')

    AP.add_argument(
            '--info',
            action='store_true',
            help='Turn on informative output')

    av = AP.parse_args()

    logformat="%(levelname)s: %(message)s"
    if av.verbose:
        log.basicConfig(format=logformat, level=log.DEBUG)
        log.info("Verbose output.")
    elif av.info:
        log.basicConfig(format=logformat, level=log.INFO)
    else:
        log.basicConfig(format=logformat)

    log.debug('input = %s' % ','.join(av.input))
    log.debug('name = %s' % av.list)
    log.debug('path = %s' % av.output)
    asset = MTAsset(*av.input, name=av.list, path=av.output)
    asset.assemble()
