#!/usr/bin/env python3
"""Call the Assembler for a Token"""

from argparse import ArgumentParser
from asset import MTAsset
import logging as log

if __name__ == '__main__':
    AP = ArgumentParser("MapTool Asset Assembler")

    AP.add_argument(
            'input',
            nargs='+',
            help='Source for creating the asset')

    AP.add_argument(
            '--output',
            help='Output directory')

    AP.add_argument(
            '--verbose',
            action='store_true',
            help='Turn on verbose output')

    av = AP.parse_args()

    if av.verbose:
        log.basicConfig(format="%(levelname)s: %(message)s", level=log.DEBUG)
        log.info("Verbose output.")
    else:
        log.basicConfig(format="%(levelname)s: %(message)s")

    asset = MTAsset()
    asset.assemble(av.input[0], path=av.output)
