[h: callbackMacroName = arg (0)]
[h: log.debug ("callback: " + callbackMacroName)]
[h: tokenId = currentToken ()]
[h: dataPackage = json.set ("",
  "actionButton", "Save Only",
  "attackFields", "Scimitar of Speed,Javelin,Longbow,Unarmed Strike,Scimitar of Speed - Raging,Javelin - Raging,Unarmed Strike - Raging,Long Bow,Storm Aura,Good Goggy" + decode ("%27") + "s Attack,Savings attacks",
  "callbackMacroLink", "macro://" + callbackMacroName + "/all/" + tokenId + "?",
  "activeAttack", "Scimitar of Speed - Raging",
  "attackName-Scimitar of Speed", "Scimitar of Speed",
  "attackBonus-Scimitar of Speed", 11,
  "damageCritical-Scimitar of Speed", 4,
  "damageRoll-Scimitar of Speed", "1d6 + 8",
  "damageType-Scimitar of Speed", "Slashing,magic",
  "attackName-Javelin", "Javelin",
  "attackBonus-Javelin", 9,
  "damageCritical-Javelin", 4,
  "damageRoll-Javelin", "1d6 + 6",
  "damageType-Javelin", "Piercing",
  "attackName-Longbow", "Longbow",
  "attackBonus-Longbow", 7,
  "damageCritical-Longbow", 1,
  "damageRoll-Longbow", "1d8 + 2",
  "damageType-Longbow", "Piercing",
  "attackName-Unarmed Strike", "Unarmed Strike",
  "attackBonus-Unarmed Strike", 9,
  "damageCritical-Unarmed Strike", 4,
  "damageRoll-Unarmed Strike", "1d1 + 6",
  "damageType-Unarmed Strike", "Bludgeoning",
  "attackName-Scimitar of Speed - Raging", "Scimitar of Speed - Raging",
  "attackBonus-Scimitar of Speed - Raging", 11,
  "damageCritical-Scimitar of Speed - Raging", 2,
  "damageRoll-Scimitar of Speed - Raging", "1d6 + 11",
  "damageType-Scimitar of Speed - Raging", "Slashing,magic",
  "attackName-Javelin - Raging", "Javelin - Raging",
  "attackBonus-Javelin - Raging", 9,
  "damageCritical-Javelin - Raging", 2,
  "damageRoll-Javelin - Raging", "1d6 + 9",
  "damageType-Javelin - Raging", "Piercing",
  "attackName-Unarmed Strike - Raging", "Unarmed Strike - Raging",
  "attackBonus-Unarmed Strike - Raging", 9,
  "damageCritical-Unarmed Strike - Raging", 2,
  "damageRoll-Unarmed Strike - Raging", "1d1 + 9",
  "damageType-Unarmed Strike - Raging", "Bludgeoning",
  "attackName-Long Bow", "Long Bow",
  "attackBonus-Long Bow", 5,
  "damageCritical-Long Bow", 1,
  "damageRoll-Long Bow", "1d8 + 1",
  "damageType-Long Bow", "Piercing",
  "attackName-Storm Aura", "Storm Aura",
  "attackBonus-Storm Aura", 0,
  "damageCritical-Storm Aura", 0,
  "damageRoll-Storm Aura", "",
  "damageType-Storm Aura", "Lightning (DC16 / half)",
  "attackName-Good Goggy" + decode ("%27") + "s Attack", "Good Goggy" + decode ("%27") + "s Attack",
  "attackBonus-Good Goggy" + decode ("%27") + "s Attack", 5,
  "damageCritical-Good Goggy" + decode ("%27") + "s Attack", 1,
  "damageRoll-Good Goggy" + decode ("%27") + "s Attack", "1d8 + 3",
  "damageType-Good Goggy" + decode ("%27") + "s Attack", "Piercing",
  "attackName-Savings attacks", "Savings attacks",
  "attackBonus-Savings attacks", 0,
  "damageCritical-Savings attacks", "",
  "damageRoll-Savings attacks", "",
  "damageType-Savings attacks", "",
  "extraDamage-Savings attacks", 2,
  "extraDamageRoll-Savings attacks-0", "3d6",
  "extraDamageType-Savings attacks-0", "Poison",
  "extraDamageSaveDC-Savings attacks-0", 16,
  "extraDamageSaveAbility-Savings attacks-0", "Constitution",
  "extraDamageSaveEffect-Savings attacks-0", "On a success take half damage",
  "extraDamageRoll-Savings attacks-1", "",
  "extraDamageType-Savings attacks-1", "",
  "extraDamageSaveDC-Savings attacks-1", 22,
  "extraDamageSaveAbility-Savings attacks-1", "Charisma",
  "extraDamageSaveEffect-Savings attacks-1", "save of fail, you die",
  "advDisadvantage", "Normal"
)]

[h: log.debug ("dataPackage before encode: " + json.indent (dataPackage))]
[h: macro.return = dataPackage]