[h: rollExpression = arg (0)]
[h: diceRolled = dnd5e_RollExpression_getDiceRolled (rollExpression)]
[h: diceSize = dnd5e_RollExpression_getDiceSize (rollExpression)]
[h: bonus = dnd5e_RollExpression_getBonus (rollExpression)]
[h, if (diceRolled > 0): baseRoll = diceRolled + "d" + diceSize; baseRoll = ""]
[h, if (bonus > 0): rollString = baseRoll + " + " + bonus; rollString = baseRoll]
[h, if (bonus < 0): rollString = baseRoll + " - " + (-1 * bonus); ""]
[h: macro.return = rollString]