[h, if (json.length (macro.args) > 0): name = arg (0); name = ""]
[h: rollExpression = dnd5e_RollExpression_setName ("", name)]
[h: rollExpression = dnd5e_RollExpression_setExpressionType (rollExpression, "Condition")]
[h: rollExpression = dnd5e_RollExpression_addType (rollExpression, dnd5e_Type_Unrollable())]
[h, if (json.length (macro.args) > 1): conditions = arg (1); conditions = ""]
[h: rollExpression = json.set(rollExpression, "saveCondition", conditions)]
[h: macro.return = rollExpression]