[h: id = arg(0)]
[h: save = arg(1)]
[h: optValue = arg(2)]
[h: save = dnd5e_RollExpression_setBonus(save, getProperty(dnd5e_RollExpression_getSaveAbility(save) + "Save", id))]
[h: save = dnd5e_RollExpression_setAdvantage(save, if(optValue == "advantage" || optValue == "both", 1, 0))]
[h: save = dnd5e_RollExpression_setDisadvantage(save, if(optValue == "disadvantage" || optValue == "both", 1, 0))]
[h: switchToken(id)]
[h: save = json.get(dnd5e_DiceRoller_roll(save, 1, 1), 0)]
[h: saveTotal = dnd5e_RollExpression_getTotal(save)]
[h: save = json.set(save, "saveResult", if(saveTotal >= dnd5e_RollExpression_getSaveDC(save, 1), "passed", "failed"))]
[h: macro.return = save]