[h: roll = arg(0)]
[h: key = getLibProperty("savedAttackRolledExpressionKey", "Lib:DnD5e")]
[h, if (isNumber(key)): key = key + 1; key = 10]
[h: setLibProperty("savedAttackRolledExpressionKey", key, "Lib:DnD5e")]
[h: roll = dnd5e_RollExpression_addTypedDescriptor(roll, "action-execution-key", "key-" + key)]
[h: macro.return = roll] 