[h, if (json.length (macro.args) > 0): name = arg (0); name = ""]
[h: rollExpression = dnd5e_RollExpression_setName ("", name)]
[h: rollExpression = dnd5e_RollExpression_setExpressionType (rollExpression, "Target Check")]
[h: rollExpression = dnd5e_RollExpression_addType (rollExpression, dnd5e_Type_Unrollable(), dnd5e_Type_Targeted())]
[h, if (json.length (macro.args) > 1): expression = arg (1); expression = ""]
[h: rollExpression = dnd5e_RollExpression_setTargetCheck(rollExpression, expression)]
[h: macro.return = rollExpression]