[h: DATA_MACRO = arg(0)]
[h: registry = arg (1)]
[h, if (argCount() > 2): libTokenName = arg (2); libTokenName = "Lib:DND5e"]
[h, token (libTokenName): libTokenId = currentToken()]
[h: macroIndex = json.get (getMacroIndexes (DATA_MACRO, "json", libTokenId), 0)]
[h: command = "[h: macro.return = '" + encode (registry) + "']"]
[h: setMacroCommand (macroIndex, command)]