[h: rollExpression = arg(0)]
[h: type = dnd5e_Type_Proficient()]
[h: rollExpression = dnd5e_RollExpression_addType (rollExpression, type)]
[h: rollExpression = json.set (rollExpression, "proficient", arg(1))]
[h: macro.return = rollExpression]