[h: log.debug(getMacroName() + ": args=" + json.indent(macro.args))]
[h: state = arg(0)]
[h: damageOutput = arg(1)]
[h: exp = arg(2)]
[h: damage = json.get(damageOutput, "damage")]
[h: state = json.set(state, "totalDamage", json.get(state, "totalDamage") + damage)]
[h: output = json.get(state, "output")]
[h: tt = dnd5e_RollExpression_getTypedDescriptor(exp, "tooltipRoll") + " = " 
		+ dnd5e_RollExpression_getTypedDescriptor(exp, "tooltipDetail") + " = " + dnd5e_RollExpression_getTotal(exp)]
[h, if (damage != dnd5e_RollExpression_getTotal(exp)): tt = tt + ", Adjusted for Save: " + damage]
[h: output = output + " <span title='" + tt + "'>Damage: " + damage + " " + capitalize(json.get(damageOutput, "type"))]
[h: applied = json.get(damageOutput, "applied")]
[h, if (applied != ""): output = output + " (" + applied + ")"; ""]
[h: output = output + "</span>"]
[h: macro.return = json.set(state, "output", output + ",")]