[h: rollExpression = dnd5e_RollExpression_setName ("", "Bless")]
[h: rollExpression = dnd5e_RollExpression_setDiceSize (rollExpression, 4)]
[h: rollExpression = dnd5e_RollExpression_setDiceRolled (rollExpression, 1)]
[h: rollExpression = dnd5e_RollExpression_setExpressionType (rollExpression, "Blessed")]
[h: macro.return = rollExpression]