[h: state = arg(0)]
[h: log.debug("dnd5e_SavedAttacks_updateState: state=" + json.indent(state))]
[h: damageOutput = arg(1)]
[h: log.debug("dnd5e_SavedAttacks_updateState: damageOutput=" + json.indent(damageOutput))]
[h: damage = json.get(damageOutput, "damage")]
[h: state = json.set(state, "totalDamage", json.get(state, "totalDamage") + damage)]
[h: output = json.get(state, "output")]
[h: output = output + " Damage: " + damage + " " + json.get(damageOutput, "type")]
[h: applied = json.get(damageOutput, "applied")]
[h, if (applied != ""): output = output + " (" + applied + ")"; ""]
[h: macro.return = json.set(state, "output", output + ",")]