[h: re = arg(0)]
[h: type = arg(1)]
[h, if (json.type (type) == "OBJECT"): typeName = json.get (type, "type"); typeName = type]
[h: newTypes = "[]"]
[h: typeKey = json.get (type , "type")]
[h: types = json.get (re, "types")]
[h: types = json.remove (types, typeKey)]
[h: re = json.set (re, "types", types)]
[h: macro.return = re]