[h: rolledExpressions = arg(0)]
[h: rolled = json.get (rolledExpressions, 0)]
[h: rolled = dnd5e_SavedAttacks_setKey (rolled)]
[h: rolled = json.set (rolled, "rollerId", currentToken())]
[h: rolledExpressions = json.set (rolledExpressions, 0, rolled)]
[h: saved = dnd5e_SavedAttacks_fetch()]
[h, if (json.isEmpty(saved)): saved = "[]"; ""]
[h: saved = json.append(saved, rolledExpressions)]
[h, while(json.length(saved) > 25): saved = json.remove(saved, 0)]
[h: setLibProperty("savedAttackRolledExpressions", saved, "Lib:DnD5e")]
[h: macro.return = rolledExpressions]